# Generated by Django 4.0.4 on 2022-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('post', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
